### ISSUE TITLE
Thanks - It works...

### ISSUE THREAD

**Issue by sladeswan** [camac/DominoDebugPlugin#3]
Installed and tested to work in
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
being the last eclispe release I installed.

**Comment by camac** [comment]
Glad to Hear it!
However note that a little while after I did this fix to the Domino Debug Plugin, it has been absorbed into the XPages SDK so if you get the latest version of [XPages SDK](https://www.openntf.org/main.nsf/project.xsp?r=project/XPages%20SDK%20for%20Eclipse%20RCP) you don't need domino debug plugin anymore (and it works with later eclipse versions)

I forgot about this project that I had here, I will update the readme so that it mentions that there is the option to just use the new XPages SDK
